# Generated by Django 4.1 on 2022-09-21 03:15

from django.db import migrations, models
import edc_utils.date


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(
                        default=edc_utils.date.get_utcnow,
                        help_text="Date and time of report.",
                        verbose_name="Report Date and Time",
                    ),
                ),
                ("report_name", models.CharField(max_length=45, verbose_name="Report Name")),
                (
                    "report_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                        verbose_name="Report Frequency",
                    ),
                ),
                (
                    "search_variable",
                    models.CharField(max_length=45, verbose_name="Search variable"),
                ),
                ("search_query", models.TextField(verbose_name="Query")),
            ],
        ),
    ]
