# Generated by Django 4.1 on 2022-09-21 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_scheduletask_options_scheduletask_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalscheduletask",
            name="search_operator",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=45,
                verbose_name="Search criteria/operators",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduletask",
            name="search_operator",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=45,
                verbose_name="Search criteria/operators",
            ),
            preserve_default=False,
        ),
    ]
